name: fintech-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scikit-learn
  - jupyter
  - matplotlib
  - seaborn
  - flask
  - django
  - dash
  - mysql-connector-python
  - kaggle
  - dotenv
  - sqlalchemy
  - psycopg2-binary
